In [78]:
# importing libraries
import geopandas as gpd
import pandas as pd
import folium
from shapely.geometry import shape
import branca

# Loading the CSV file and the shapefile
crime_df = pd.read_csv('./datasets/registered_crime/registered_crime.csv', sep=';', low_memory=False) #Adding "low_memory=False" to prevent warning
cbs = gpd.read_file('./datasets/boa/cbs_breda_grid.gpkg')
shapefile = gpd.read_file('./datasets/shapefiles/Buurten.shp')

crime_df #Displaying the dataframe

,Soort misdrijf,Perioden,Wijken en buurten,Geregistreerde misdrijven (aantal)
0,Totaal misdrijven,2012 januari,Breda,1382
1,Totaal misdrijven,2012 februari,Breda,1284
2,Totaal misdrijven,2012 maart,Breda,1375
3,Totaal misdrijven,2012 april,Breda,1341
4,Totaal misdrijven,2012 mei,Breda,1455
...,...,...,...,...
545627,3.9.3 Fraude (overig),2022 december,Buitengebied Teteringen,0
545628,3.9.3 Fraude (overig),2023 januari,Buitengebied Teteringen,0
545629,3.9.3 Fraude (overig),2023 februari,Buitengebied Teteringen,0
545630,3.9.3 Fraude (overig),2023 maart,Buitengebied Teteringen,0
545631,3.9.3 Fraude (overig),2023 april,Buitengebied Teteringen,0

In [59]:
cbs['neighborhood_name'].unique()

array(['Buitengebied Prinsenbeek', 'Liesbos', 'Prinsenbeek', 'Effen-Rith',
       'Hagebeemd', 'Muizenberg', 'Kesteren', 'Kroeten', 'Steenakker',
       'Princenhage', 'Overkroeten', 'Heilaar', 'Gageldonk', 'Heksenwiel',
       'Hazeldonk', 'Westerpark', 'Kievitsloop', 'Mastbos', 'Heuvel',
       'Ruitersbos', 'Tuinzigt', 'Emer', 'Haagpoort', 'Boeimeer',
       'Fellenoord', 'Schorsmolen', 'Krogten', 'Belcrum', 'City',
       'Chasse', 'Station', 'Zandberg', 'Wisselaar', 'Ginneken',
       'Biesdonk', 'Valkenberg', 'Doornbos-Linie', 'Sportpark',
       'Blauwe Kei', 'Buitengebied Ulvenhout', 'Brabantpark',
       'Geeren-Zuid', 'Geeren-Noord', 'Ulvenhout', 'Overakker',
       'Vuchtpolder', 'Ypelaar', 'Waterdonken', 'Teteringen',
       'Nieuw Wolfslaar', 'Buitengebied Bavel', 'Heusdenhout',
       'Moleneind-Oost', 'Buitengebied Teteringen', 'Bavel', 'Hoogeind'],
      dtype=object)

In [60]:
crime_df['Wijken en buurten'].unique()

array(['Breda', 'Breda centrum', 'Valkenberg', 'Chassé', 'Fellenoord',
       'Schorsmolen', 'Station', 'City', 'Breda noord', 'Belcrum',
       'Doornbos-Linie', 'Biesdonk', 'Geeren-zuid', 'Wisselaar',
       'Krogten', 'Geeren-noord', 'Waterdonken', 'Breda oost',
       'Brabantpark', 'Sportpark', 'Zandberg', 'Heusdenhout',
       'Moleneind-oost', 'Hoogeind', 'Breda zuid-oost', 'Blauwe Kei',
       'Ypelaar', 'Overakker', 'Ginneken', 'Mastbos', 'Breda zuid',
       'Boeimeer', 'Ruitersbos', 'Breda west', 'Haagpoort', 'Heuvel',
       'Tuinzigt', 'Princenhage', 'Westerpark', 'Heilaar', 'Hazeldonk',
       'Steenakker', 'Effen-Rith', 'Liesbos', 'Breda noord-west',
       'Gageldonk', 'Kievitsloop', 'Kesteren', 'Muizenberg', 'Heksenwiel',
       'Overkroeten', 'Kroeten', 'Emer', 'Hagebeemd', 'Bavel',
       'Nieuw Wolfslaar', 'Buitengebied Bavel', 'Ulvenhout',
       'Buitengebied Ulvenhout', 'Prinsenbeek',
       'Buitengebied Prinsenbeek', 'Teteringen', 'Vuchtpolder',
       'Buitengebied Teteringen'], dtype=object)

In [61]:
# Delete rows where "Wijken en buurten" is "Breda"
# Delete rows where "Soort misdrijf" is "Totaal misdrijven"
crime_df = crime_df[crime_df['Wijken en buurten'] != 'Breda']
crime_df = crime_df[crime_df['Soort misdrijf'] != 'Totaal misdrijven']

# Reset the index
crime_df.reset_index(drop=True, inplace=True)

# Display the dataframe to see if the code worked
crime_df

,Soort misdrijf,Perioden,Wijken en buurten,Geregistreerde misdrijven (aantal)
0,1.1.1 Diefstal/inbraak woning,2012 januari,Breda centrum,7
1,1.1.1 Diefstal/inbraak woning,2012 februari,Breda centrum,8
2,1.1.1 Diefstal/inbraak woning,2012 maart,Breda centrum,4
3,1.1.1 Diefstal/inbraak woning,2012 april,Breda centrum,15
4,1.1.1 Diefstal/inbraak woning,2012 mei,Breda centrum,4
...,...,...,...,...
528491,3.9.3 Fraude (overig),2022 december,Buitengebied Teteringen,0
528492,3.9.3 Fraude (overig),2023 januari,Buitengebied Teteringen,0
528493,3.9.3 Fraude (overig),2023 februari,Buitengebied Teteringen,0
528494,3.9.3 Fraude (overig),2023 maart,Buitengebied Teteringen,0
528495,3.9.3 Fraude (overig),2023 april,Buitengebied Teteringen,0